;;;; tests/nn.lisp -- mlx.nn and mlx.optimizers
;;;;
;;;; The *-REFERENCE tables were produced by Python MLX 0.32.1 (mlx.nn,
;;;; mlx.optimizers) on the same inputs, so these tests check parity.

(in-package :mlx-tests)

(def-suite :mlx.nn :in :mlx)
(in-suite :mlx.nn)

(defparameter *activation-reference*
  '(
    ("relu" 0.0 0.0 0.0 0.7 3.0)
    ("relu6" 0.0 0.0 0.0 2.1 6.0)
    ("leaky-relu" -0.02 -0.005 0.0 0.7 3.0)
    ("elu" -0.864665 -0.393469 0.0 0.7 3.0)
    ("selu" -1.520162 -0.691756 0.0 0.73549 3.1521)
    ("celu" -0.864665 -0.393469 0.0 0.7 3.0)
    ("gelu" -0.0455 -0.154269 0.0 0.530625 2.99595)
    ("gelu-approx" -0.045402 -0.154286 0.0 0.53057 2.996363)
    ("gelu-fast-approx" -0.064341 -0.149612 0.0 0.536894 2.981929)
    ("silu" -0.238406 -0.18877 0.0 0.467731 2.857722)
    ("mish" -0.252501 -0.220744 0.0 0.561148 2.986535)
    ("softplus" 0.126928 0.474077 0.693147 1.103186 3.048587)
    ("softsign" -0.666667 -0.333333 0.0 0.411765 0.75)
    ("log-sigmoid" -2.126928 -0.974077 -0.693147 -0.403186 -0.048587)
    ("hardswish" -0.333333 -0.208333 0.0 0.431667 3.0)
    ("hard-tanh" -1.0 -0.5 0.0 0.7 1.0)
    ("log-softmax" -5.171413 -3.671413 -3.171413 -2.471413 -0.171413)
    ("step" 0.0 0.0 1.0 1.0 1.0)
))
(defparameter *loss-reference*
  '(
    ("ce" 0.241311 0.109601)
    ("ce-probs" 0.841311 0.389601)
    ("ce-smooth" 0.391311 0.299601)
    ("bce" 0.304756)
    ("bce-probs" 0.279777)
    ("nll" 0.241311 0.109601)
    ("mse" 0.5)
    ("l1" 0.666667)
    ("smooth-l1" 0.25)
    ("huber" 0.125 0.5 0.125)
    ("kl" 0.119689 0.179489)
    ("log-cosh" 0.120115 0.433781 0.120115)
    ("cosine" 0.831479 0.998476)
    ("hinge" 0.5 0.0 0.0)
))
(defparameter *optimizer-reference*
  '(
    ("sgd" 1.005 -2.02 0.46)
    ("sgd-momentum" 0.977838 -1.993564 0.432063)
    ("sgd-nesterov" 0.99006 -2.02423 0.40132)
    ("rmsprop" 0.942573 -1.999885 0.364465)
    ("adagrad" 0.942566 -1.999612 0.364543)
    ("adadelta" 0.999061 -2.001674 0.494924)
    ("adam" 0.389788 -1.900672 -0.243908)
    ("adam-bc" 0.827418 -1.946556 0.309835)
    ("adamw" 0.387819 -1.895228 -0.244661)
    ("adamax" 0.979686 -1.99868 0.473596)
    ("lion" 0.897303 -2.094106 0.398601)
))
(defparameter *schedule-reference*
  '(("cosine" 1.0 0.55 0.1 0.1)
    ("exp" 1.0 0.9 0.59049)
    ("step" 1.0 1.0 0.5 0.25)
    ("linear" 0.0 0.5 1.0 1.0)))

(defun reference (table name) (rest (assoc name table :test #'string=)))

(test activations-match-python-mlx
  (let ((x (mx:from-lisp '(-2.0 -0.5 0.0 0.7 3.0))))
    (loop for (name fn) in `(("relu" ,#'nn:relu) ("relu6" ,(lambda (x) (nn:relu6 (mx:multiply x 3))))
                             ("leaky-relu" ,#'nn:leaky-relu) ("elu" ,#'nn:elu) ("selu" ,#'nn:selu)
                             ("celu" ,#'nn:celu) ("gelu" ,#'nn:gelu) ("gelu-approx" ,#'nn:gelu-approx)
                             ("gelu-fast-approx" ,#'nn:gelu-fast-approx) ("silu" ,#'nn:silu)
                             ("mish" ,#'nn:mish) ("softplus" ,#'nn:softplus) ("softsign" ,#'nn:softsign)
                             ("log-sigmoid" ,#'nn:log-sigmoid) ("hardswish" ,#'nn:hardswish)
                             ("hard-tanh" ,#'nn:hard-tanh) ("log-softmax" ,#'nn:log-softmax)
                             ("step" ,#'nn:step))
          do (is (close-to (funcall fn x) (reference *activation-reference* name) 1e-4)
                 "activation ~A" name)))
  (is (close-to (nn:glu (mx:from-lisp '(1.0 2.0 0.0 100.0))) '(0.5 2.0) 1e-4))
  (is (close-to (nn:softmax (mx:from-lisp '((0.0 0.0)))) '((0.5 0.5)))))

(test losses-match-python-mlx
  (let* ((logits (mx:from-lisp '((2.0 0.5 -1.0) (0.1 0.2 3.0))))
         (targets (mx:from-lisp '(0 2)))
         (probs (mx:from-lisp '((0.7 0.2 0.1) (0.0 0.1 0.9))))
         (p (mx:from-lisp '(0.5 -1.0 2.0)))
         (tt (mx:from-lisp '(1.0 0.0 1.5)))
         (lp (nn:log-softmax logits))
         (lq (nn:log-softmax (mx:multiply logits 0.5))))
    (flet ((check (name value)
             (is (close-to value (let ((r (reference *loss-reference* name)))
                                   (if (= (mx:ndim value) 0) (first r) r))
                           1e-4)
                 "loss ~A" name)))
      (check "ce" (nn:cross-entropy logits targets))
      (check "ce-probs" (nn:cross-entropy logits probs))
      (check "ce-smooth" (nn:cross-entropy logits targets :label-smoothing 0.1))
      (check "bce" (nn:binary-cross-entropy p (mx:from-lisp '(1.0 0.0 1.0))))
      (check "bce-probs" (nn:binary-cross-entropy (mx:from-lisp '(0.9 0.2 0.6)) (mx:from-lisp '(1.0 0.0 1.0))
                                                  :with-logits nil))
      (check "nll" (nn:nll-loss lp targets))
      (check "mse" (nn:mse-loss p tt))
      (check "l1" (nn:l1-loss p tt))
      (check "smooth-l1" (nn:smooth-l1-loss p tt))
      (check "huber" (nn:huber-loss p tt))
      (check "kl" (nn:kl-div-loss lp lq))
      (check "log-cosh" (nn:log-cosh-loss p tt))
      (check "cosine" (nn:cosine-similarity-loss logits probs))
      (check "hinge" (nn:hinge-loss p (mx:from-lisp '(1.0 -1.0 1.0)))))
    (is (close-to (nn:cross-entropy logits targets :reduction :mean) (/ (+ 0.241311 0.109601) 2) 1e-4))
    (is (close-to (nn:cross-entropy logits targets :reduction :sum) (+ 0.241311 0.109601) 1e-4))))

(test optimizers-match-python-mlx
  (loop for (name make) in `(("sgd" ,(lambda () (optim:sgd 0.1)))
                             ("sgd-momentum" ,(lambda () (optim:sgd 0.1 :momentum 0.9 :weight-decay 0.01)))
                             ("sgd-nesterov" ,(lambda () (optim:sgd 0.1 :momentum 0.9 :nesterov t)))
                             ("rmsprop" ,(lambda () (optim:rmsprop 0.01)))
                             ("adagrad" ,(lambda () (optim:adagrad 0.1)))
                             ("adadelta" ,(lambda () (optim:adadelta 1.0)))
                             ("adam" ,(lambda () (optim:adam 0.1)))
                             ("adam-bc" ,(lambda () (optim:adam 0.1 :bias-correction t)))
                             ("adamw" ,(lambda () (optim:adamw 0.1)))
                             ("adamax" ,(lambda () (optim:adamax 0.1)))
                             ("lion" ,(lambda () (optim:lion 0.1 :weight-decay 0.01))))
        do (let ((opt (funcall make))
                 (params (list :w (mx:from-lisp '(1.0 -2.0 0.5)))))
             (dolist (g '((0.1 -0.3 0.2) (0.05 0.4 -0.1) (-0.2 0.1 0.3)))
               (setf params (optim:apply-gradients opt (list :w (mx:from-lisp g)) params)))
             (is (= 3 (optim:step-count opt)))
             (is (close-to (getf params :w) (reference *optimizer-reference* name) 1e-4)
                 "optimizer ~A" name))))

(test schedules-match-python-mlx
  (flet ((values-of (schedule steps) (mapcar schedule steps)))
    (is (approx= (values-of (optim:cosine-decay 1.0 10 :end 0.1) '(0 5 10 15))
                 (reference *schedule-reference* "cosine")))
    (is (approx= (values-of (optim:exponential-decay 1.0 0.9) '(0 1 5)) (reference *schedule-reference* "exp")))
    (is (approx= (values-of (optim:step-decay 1.0 0.5 3) '(0 2 3 7)) (reference *schedule-reference* "step")))
    (is (approx= (values-of (optim:linear-schedule 0.0 1.0 4) '(0 2 4 9)) (reference *schedule-reference* "linear")))
    (let ((joined (optim:join-schedules (list (optim:linear-schedule 0 1 10) (optim:cosine-decay 1.0 100)) '(10))))
      (is (approx= 0.5 (funcall joined 5)))
      (is (approx= 1.0 (funcall joined 10)))))
  (let ((opt (optim:sgd (optim:exponential-decay 1.0 0.5))))
    (is (approx= 1.0 (optim:learning-rate opt)))
    (optim:apply-gradients opt (list (mx:scalar 1.0)) (list (mx:scalar 0.0)))
    (is (approx= 0.5 (optim:learning-rate opt)))))

(test clip-grad-norm
  (let ((grads (list :a (mx:from-lisp '(3.0 4.0)) :b (mx:from-lisp '(12.0)))))
    (multiple-value-bind (clipped norm) (optim:clip-grad-norm grads 6.5)
      (is (close-to norm 13.0))
      (is (close-to (getf clipped :a) '(1.5 2.0)))
      (is (close-to (getf clipped :b) '(6.0))))
    (is (close-to (getf (optim:clip-grad-norm grads 100) :a) '(3 4)))))

;;; Module protocol

(nn:defmodule mlp ()
  ())

(defun make-mlp (in hidden out)
  (let ((m (make-instance 'mlp)))
    (nn:register m :layers (list (nn:linear in hidden) (nn:linear hidden out)))
    m))

(defmethod nn:forward ((m mlp) &rest args)
  (destructuring-bind (l1 l2) (nn:child m :layers)
    (funcall l2 (nn:relu (funcall l1 (first args))))))

(test module-protocol
  (let ((m (make-mlp 3 4 2)))
    (is (typep m 'nn:module))
    (is (equal '(5 2) (mx:shape (funcall m (mx:ones '(5 3))))))
    (is (equal '("layers.0.bias" "layers.0.weight" "layers.1.bias" "layers.1.weight")
               (mapcar #'car (nn:flatten-parameters m))))
    (is (= (+ 12 4 8 2) (nn:parameter-count m)))
    (is (= 3 (length (nn:modules m))))
    (is (hash-table-p (nn:parameters m)))
    (is (= 2 (length (gethash "layers" (nn:parameters m)))))
    (is (eq (first (nn:child m "layers")) (first (nn:child m :layers))))
    (let ((paths '()))
      (nn:apply-to-modules (lambda (path mod) (declare (ignore mod)) (push path paths)) m)
      (is (equal '("" "layers.0" "layers.1") (reverse paths))))
    (is (search "2 layers" (with-output-to-string (s) (nn:summary (nn:sequential #'nn:relu #'nn:relu) s))))))

(test update-and-tree-map
  (let* ((m (nn:linear 2 2))
         (zeroed (mx:tree-map #'mx:zeros-like (nn:parameters m))))
    (nn:update m zeroed)
    (is (close-to (funcall m (mx:ones '(1 2))) '((0 0))))
    ;; partial trees leave other parameters alone
    (let ((only-bias (make-hash-table :test 'equal)))
      (setf (gethash "bias" only-bias) (mx:ones '(2)))
      (nn:update m only-bias)
      (is (close-to (funcall m (mx:ones '(1 2))) '((1 1)))))))

(test freezing
  (let ((m (make-mlp 2 3 1)))
    (nn:freeze m)
    (is (zerop (hash-table-count (nn:trainable-parameters m))))
    (nn:unfreeze m)
    (is (= 4 (length (nn:flatten-parameters (nn:trainable-parameters m)))))
    (nn:freeze m :keys '(:bias))
    (is (equal '("layers.0.weight" "layers.1.weight")
               (mapcar #'car (nn:flatten-parameters (nn:trainable-parameters m)))))
    (is (= 4 (length (nn:flatten-parameters m))) "frozen arrays are still parameters")))

(test weights-roundtrip
  (with-temp-file (f "w.safetensors")
    (let ((a (make-mlp 3 4 2)) (b (make-mlp 3 4 2)) (x (random:normal :shape '(2 3))))
      (nn:save-weights a f)
      (nn:load-weights b f)
      (is (close-to (funcall b x) (lisp (funcall a x))))
      ;; strict loading checks names and shapes
      (signals error (nn:load-weights (make-mlp 3 5 2) f))
      (signals error (nn:load-weights b (list (cons "nope.weight" (mx:ones '(2))))))
      (finishes (nn:load-weights b (list (cons "nope.weight" (mx:ones '(2)))) :strict nil))
      (nn:load-weights b (list (cons "layers.1.bias" '(7.0 8.0))) :strict nil)
      (is (close-to (nn:child (second (nn:child b :layers)) :bias) '(7 8))))))

(test value-and-grad-restores-model
  (let* ((m (nn:linear 2 1))
         (before (nn:child m "weight"))
         (vg (nn:value-and-grad m (lambda (x) (mx:sum (funcall m x))))))
    (multiple-value-bind (loss grads) (funcall vg (mx:ones '(3 2)))
      (is (= 0 (mx:ndim loss)))
      (is (close-to (gethash "weight" grads) '((3 3))))
      (is (close-to (gethash "bias" grads) '(3))))
    (is (eq before (nn:child m "weight")) "the model's own arrays are put back")))

;;; Layers

(test layer-shapes
  (let ((x4 (random:normal :shape '(2 8 8 3))))
    (is (equal '(2 8 8 16) (mx:shape (funcall (nn:conv2d 3 16 3 :padding 1) x4))))
    (is (equal '(2 4 4 16) (mx:shape (funcall (nn:conv2d 3 16 '(3 3) :stride 2 :padding 1) x4))))
    (is (equal '(2 6 4) (mx:shape (funcall (nn:conv1d 3 4 3) (random:normal :shape '(2 8 3))))))
    (is (equal '(2 4 4 3) (mx:shape (funcall (nn:max-pool-2d 2) x4))))
    (is (equal '(2 4 4 3) (mx:shape (funcall (nn:avg-pool-2d 3 :stride 2 :padding 1) x4))))
    (is (equal '(2 7 3) (mx:shape (funcall (nn:max-pool-1d 2 :stride 1) (random:normal :shape '(2 8 3))))))
    (is (equal '(2 5 16) (mx:shape (funcall (nn:embedding 10 16) (mx:from-lisp '((1 2 3 4 5) (0 0 0 0 0)))))))
    (is (equal '(2 10) (mx:shape (nn:as-linear (nn:embedding 10 16) (mx:ones '(2 16))))))
    (is (equal '(4 8) (mx:shape (funcall (nn:prelu) (mx:ones '(4 8))))))
    (is (equal '(3 2) (mx:shape (funcall (nn:sequential (nn:linear 4 8) #'nn:gelu (nn:identity) (nn:linear 8 2))
                                         (mx:ones '(3 4))))))))

(test pooling-values
  (let ((x (mx:reshape (mx:arange 16.0) '(1 4 4 1))))
    (is (close-to (mx:squeeze (funcall (nn:max-pool-2d 2) x)) '((5 7) (13 15))))
    (is (close-to (mx:squeeze (funcall (nn:avg-pool-2d 2) x)) '((2.5 4.5) (10.5 12.5))))))

(test normalization
  (let ((x (random:normal :shape '(4 16) :loc 3.0 :scale 2.0)))
    (is (close-to (mx:mean (funcall (nn:layer-norm 16) x) :axis -1) '(0 0 0 0) 1e-3))
    (is (close-to (mx:mean (mx:square (funcall (nn:rms-norm 16) x)) :axis -1) '(1 1 1 1) 1e-2))
    (is (equal '(2 3 16) (mx:shape (funcall (nn:group-norm 4 16) (random:normal :shape '(2 3 16))))))
    (let ((bn (nn:batch-norm 16)))
      (is (close-to (mx:mean (funcall bn x) :axis 0) (make-list 16 :initial-element 0) 1e-3))
      (is (not (member "running_mean" (mapcar #'car (nn:flatten-parameters (nn:trainable-parameters bn)))
                       :test #'string=)))
      (is (> (mx:item (mx:mean (nn:child bn "running_mean"))) 0.1) "running stats updated")
      (nn:train-mode bn nil)
      (is (equal '(4 16) (mx:shape (funcall bn x)))))))

(test dropout-modes
  (let ((d (nn:dropout 0.5)) (x (mx:ones '(1000))))
    (let ((y (lisp (funcall d x))))
      (is (every (lambda (v) (or (= v 0) (= v 2))) y))
      (is (< 300 (count 0.0 y) 700)))
    (nn:train-mode d nil)
    (is (not (nn:training-p d)))
    (is (close-to (mx:sum (funcall d x)) 1000))
    (signals error (nn:dropout 2))))

(test attention
  (let ((mha (nn:multi-head-attention 16 4))
        (x (random:normal :shape '(2 5 16))))
    (is (equal '(2 5 16) (mx:shape (funcall mha x x x))))
    ;; an explicit additive causal mask agrees with the fused causal mode
    (is (close-to (funcall mha x x x :mask :causal)
                  (lisp (funcall mha x x x :mask (nn:create-additive-causal-mask 5)))
                  1e-3))
    ;; causality: position 0 ignores later positions
    (let ((x2 (mx:concatenate (list (mx:ref x t '(0 1)) (random:normal :shape '(2 4 16))) :axis 1)))
      (is (close-to (mx:ref (funcall mha x2 x2 x2 :mask :causal) t 0)
                    (lisp (mx:ref (funcall mha x x x :mask :causal) t 0)) 1e-3))))
  (is (equal '(1 2 4 8) (mx:shape (funcall (nn:rope 8) (mx:ones '(1 2 4 8)) :offset 3)))))

(test quantization
  (let* ((lin (nn:linear 64 32))
         (x (random:normal :shape '(4 64)))
         (exact (funcall lin x))
         (m (nn:sequential lin (nn:embedding 10 64))))
    (nn:quantize m :group-size 32 :bits 8)
    (destructuring-bind (ql qe) (nn:child m "layers")
      (is (typep ql 'nn:quantized-linear))
      (is (typep qe 'nn:quantized-embedding))
      (is (< (mx:item (mx:max (mx:abs (mx:subtract (funcall ql x) exact)))) 0.05))
      (is (equal '(3 64) (mx:shape (funcall qe (mx:from-lisp '(1 2 3))))))
      (is (equal '(2 10) (mx:shape (nn:as-linear qe (mx:ones '(2 64))))))
      (is (= 1 (length (nn:flatten-parameters (nn:trainable-parameters m)))) "only the bias trains"))))

(test initializers
  (let ((w (mx:zeros '(64 32))))
    (is (close-to (funcall (nn:init-constant 3.0) (mx:zeros '(2))) '(3 3)))
    (is (equal '(64 32) (mx:shape (funcall (nn:glorot-uniform) w))))
    (let ((limit (sqrt (/ 6.0 96))))
      (is (<= (mx:item (mx:max (mx:abs (funcall (nn:glorot-uniform) w)))) limit)))
    (is (close-to (mx:std (funcall (nn:he-normal) (mx:zeros '(256 256)))) (/ 1 16.0) 0.05))
    (is (< (abs (mx:item (mx:mean (funcall (nn:glorot-normal) w)))) 0.05))
    (is (<= (mx:item (mx:max (mx:abs (funcall (nn:he-uniform) w)))) (sqrt (/ 3.0 32))))
    (is (close-to (funcall (nn:init-identity) (mx:zeros '(2 2))) '((1 0) (0 1))))
    (is (close-to (mx:mean (funcall (nn:init-normal :mean 5.0) w)) 5 0.02))
    (is (<= 2.0 (mx:item (mx:min (funcall (nn:init-uniform :low 2.0 :high 3.0) w)))))))

;;; Training end to end

(test training-converges-with-flat-memory
  (random:seed 3)
  (let* ((model (make-mlp 2 16 1))
         (x (mx:from-lisp '((0 0) (0 1) (1 0) (1 1)) :dtype :float32))
         (y (mx:from-lisp '((0) (1) (1) (0)) :dtype :float32))
         (opt (optim:adam 0.05))
         (step (nn:value-and-grad model (lambda () (nn:binary-cross-entropy (funcall model x) y))))
         (memory '())
         (baseline (progn (sb-ext:gc :full t) (sb-kernel:run-pending-finalizers) (mx:active-memory))))
    (dotimes (i 300)
      (mx:with-scope ()
        (multiple-value-bind (loss grads) (funcall step)
          (declare (ignore loss))
          (optim:update opt model grads)
          (mx:eval (nn:parameters model) (optim:state opt))))
      (push (mx:active-memory) memory))
    (is (close-to (mx:round (mx:sigmoid (funcall model x))) '((0) (1) (1) (0))))
    ;; the model and optimizer state are ~1 KB; without prompt freeing,
    ;; every step's arrays would pile up until the next GC
    (is (< (- (reduce #'max memory) baseline) 16384)
        "memory stays bounded (grew ~D bytes)" (- (reduce #'max memory) baseline))
    (is (= 300 (optim:step-count opt)))))

(test optimizers-on-models
  (dolist (make (list (lambda () (optim:sgd 0.1 :momentum 0.9)) (lambda () (optim:adamw 0.01))
                      (lambda () (optim:rmsprop 0.01)) (lambda () (optim:lion 0.05))))
    (random:seed 0)
    (let* ((model (nn:linear 3 1))
           (x (random:normal :shape '(32 3)))
           (y (mx:matmul x (mx:from-lisp '((1.0) (-2.0) (0.5)))))
           (loss (lambda () (nn:mse-loss (funcall model x) y)))
           (step (nn:value-and-grad model loss))
           (opt (funcall make))
           (initial (mx:item (funcall loss))))
      (dotimes (i 50)
        (mx:with-scope ()
          (optim:update opt model (nth-value 1 (funcall step)))
          (mx:eval (nn:parameters model))))
      (is (< (mx:item (funcall loss)) (* 0.5 initial)) "~A reduces the loss" (type-of opt)))))
