;;;; tests/ops.lisp -- the generated array operations and their dispatchers

(in-package :mlx-tests)

(def-suite :mlx.ops :in :mlx)
(in-suite :mlx.ops)

(test arithmetic
  (let ((a (mx:from-lisp '(1.0 2.0 3.0)))
        (b (mx:from-lisp '(4.0 5.0 6.0))))
    (is (close-to (mx:add a b) '(5 7 9)))
    (is (close-to (mx:subtract a b) '(-3 -3 -3)))
    (is (close-to (mx:multiply a b) '(4 10 18)))
    (is (close-to (mx:divide b a) '(4 2.5 2)))
    (is (close-to (mx:power a 2) '(1 4 9)))
    (is (close-to (mx:negative a) '(-1 -2 -3)))
    (is (close-to (mx:maximum a 2) '(2 2 3)))
    (is (close-to (mx:minimum a 2) '(1 2 2)))
    (is (close-to (mx:floor-divide b a) '(4 2 2)))
    (is (close-to (mx:remainder b a) '(0 1 0)))
    (is (close-to (mx:addmm (mx:ones '(2 2)) (mx:ones '(2 2)) (mx:ones '(2 2)) :alpha 2.0 :beta 1.0)
                  '((5 5) (5 5))))))

(test lisp-scalars-and-weak-typing
  (is (close-to (mx:add 1 (mx:from-lisp '(1.0 2.0))) '(2 3)))
  (is (close-to (mx:subtract 10 (mx:from-lisp '(1 2))) '(9 8)))
  (is (eq :float16 (mx:dtype (mx:add (mx:ones '(2) :dtype :float16) 1.0))))
  (is (eq :int8 (mx:dtype (mx:multiply (mx:ones '(2) :dtype :int8) 3))))
  (is (eq :float32 (mx:dtype (mx:add (mx:arange 3) 0.5))))
  (is (eq :int32 (mx:dtype (mx:add 1 2))))
  ;; Lisp data is accepted wherever an array is
  (is (close-to (mx:add '(1 2) #(3 4)) '(4 6))))

(test unary-math
  (let ((x (mx:from-lisp '(0.0 1.0 4.0))))
    (is (close-to (mx:sqrt x) '(0 1 2)))
    (is (close-to (mx:square x) '(0 1 16)))
    (is (close-to (mx:exp (mx:scalar 0.0)) 1))
    (is (close-to (mx:log (mx:scalar 1.0)) 0))
    (is (close-to (mx:abs (mx:from-lisp '(-1 2))) '(1 2)))
    (is (close-to (mx:sin (mx:scalar 0.0)) 0))
    (is (close-to (mx:cos (mx:scalar 0.0)) 1))
    (is (close-to (mx:tanh (mx:scalar 0.0)) 0))
    (is (close-to (mx:sigmoid (mx:scalar 0.0)) 0.5))
    (is (close-to (mx:reciprocal (mx:scalar 4.0)) 0.25))
    (is (close-to (mx:rsqrt (mx:scalar 4.0)) 0.5))
    (is (close-to (mx:floor (mx:from-lisp '(1.5 -1.5))) '(1 -2)))
    (is (close-to (mx:ceil (mx:from-lisp '(1.5 -1.5))) '(2 -1)))
    (is (close-to (mx:round (mx:from-lisp '(1.234 5.678)) :decimals 1) '(1.2 5.7)))
    (is (close-to (mx:sign (mx:from-lisp '(-3 0 3))) '(-1 0 1)))
    (is (close-to (mx:erf (mx:scalar 0.0)) 0))
    (is (close-to (mx:log1p (mx:scalar 0.0)) 0))
    (is (close-to (mx:arctan2 (mx:scalar 1.0) (mx:scalar 1.0)) (/ pi 4)))))

(test comparisons-and-logic
  (let ((a (mx:from-lisp '(1 2 3))))
    (is (equal '(nil t nil) (lisp (mx:equal a 2))))
    (is (equal '(t nil t) (lisp (mx:not-equal a 2))))
    (is (equal '(nil nil t) (lisp (mx:greater a 2))))
    (is (equal '(t t nil) (lisp (mx:less-equal a 2))))
    (is (equal '(nil t t) (lisp (mx:logical-or (mx:greater a 2) (mx:equal a 2)))))
    (is (equal '(t nil nil) (lisp (mx:logical-not (mx:greater-equal a 2)))))
    (is (eq t (mx:item (mx:array-equal a (mx:from-lisp '(1 2 3))))))
    (is (eq t (mx:item (mx:allclose (mx:from-lisp '(1.0)) (mx:from-lisp '(1.000001))))))
    (is (equal '(t nil) (lisp (mx:isnan (mx:divide (mx:from-lisp '(0.0 1.0)) (mx:from-lisp '(0.0 1.0)))))))
    (is (equal '(nil t) (lisp (mx:isinf (mx:divide (mx:from-lisp '(1.0 1.0)) (mx:from-lisp '(1.0 0.0)))))))
    (is (close-to (mx:where (mx:greater a 1) a 0) '(0 2 3)))
    (is (close-to (mx:bitwise-and (mx:from-lisp '(12)) (mx:from-lisp '(10))) '(8)))
    (is (close-to (mx:left-shift (mx:from-lisp '(1)) (mx:from-lisp '(3))) '(8)))))

(test reductions
  (let ((a (mx:from-lisp '((1.0 2.0) (3.0 4.0)))))
    (is (= 10 (mx:item (mx:sum a))))
    (is (close-to (mx:sum a :axis 0) '(4 6)))
    (is (close-to (mx:sum a :axis 1) '(3 7)))
    (is (close-to (mx:sum a :axis '(0 1)) 10))
    (is (equal '(1 2) (mx:shape (mx:sum a :axis 0 :keepdims t))))
    (is (close-to (mx:mean a) 2.5))
    (is (close-to (mx:prod a) 24))
    (is (close-to (mx:max a) 4))
    (is (close-to (mx:min a :axis 1) '(1 3)))
    (is (close-to (mx:var a) 1.25))
    (is (close-to (mx:std (mx:from-lisp '(1.0 3.0)) :ddof 1) (sqrt 2)))
    (is (close-to (mx:logsumexp (mx:from-lisp '(0.0 0.0))) (log 2)))
    (is (= 3 (mx:item (mx:argmax (mx:from-lisp '(1 5 2 9))))))
    (is (close-to (mx:argmin a :axis 1) '(0 0)))
    (is (eq t (mx:item (mx:all (mx:greater a 0)))))
    (is (eq nil (mx:item (mx:any (mx:greater a 10)))))
    (is (close-to (mx:cumsum (mx:from-lisp '(1 2 3)) 0) '(1 3 6)))
    (is (close-to (mx:cumprod (mx:from-lisp '(1 2 3)) 0 :reverse t) '(6 6 3)))
    (is (close-to (mx:median (mx:from-lisp '(3.0 1.0 2.0)) '(0)) 2))))

(test creation
  (is (equal '(2 3) (mx:shape (mx:zeros '(2 3)))))
  (is (close-to (mx:ones '(2)) '(1 1)))
  (is (eq :int32 (mx:dtype (mx:zeros '(2) :dtype :int32))))
  (is (close-to (mx:full '(2) 7) '(7 7)))
  (is (eq :int32 (mx:dtype (mx:full '(2) 7))))
  (is (eq :float32 (mx:dtype (mx:full '(2) 7.0))))
  (is (close-to (mx:arange 4) '(0 1 2 3)))
  (is (eq :int32 (mx:dtype (mx:arange 4))))
  (is (close-to (mx:arange 1 3) '(1 2)))
  (is (close-to (mx:arange 0 1 0.25) '(0 0.25 0.5 0.75)))
  (is (eq :float32 (mx:dtype (mx:arange 0 1 0.25))))
  (is (eq :float16 (mx:dtype (mx:arange 3 :dtype :float16))))
  (is (close-to (mx:linspace 0 1 :num 3) '(0 0.5 1)))
  (is (close-to (mx:eye 2) '((1 0) (0 1))))
  (is (close-to (mx:eye 2 :m 3 :k 1) '((0 1 0) (0 0 1))))
  (is (close-to (mx:identity 2) '((1 0) (0 1))))
  (is (close-to (mx:tri 2) '((1 0) (1 1))))
  (is (close-to (mx:zeros-like (mx:ones '(2))) '(0 0)))
  (is (close-to (mx:ones-like (mx:zeros '(2))) '(1 1)))
  (is (close-to (mx:full-like (mx:zeros '(2)) 3) '(3 3))))

(test shape-manipulation
  (let ((a (mx:arange 6)))
    (is (equal '(2 3) (mx:shape (mx:reshape a '(2 3)))))
    (is (equal '(3 2) (mx:shape (mx:reshape a '(-1 2)))))
    (is (equal '(3 2) (mx:shape (mx:transpose (mx:reshape a '(2 3))))))
    (is (equal '(3 1 2) (mx:shape (mx:transpose (mx:zeros '(1 2 3)) :axes '(2 0 1)))))
    (is (equal '(6) (mx:shape (mx:flatten (mx:reshape a '(2 3))))))
    (is (equal '(1 6) (mx:shape (mx:expand-dims a 0))))
    (is (equal '(1 6 1) (mx:shape (mx:expand-dims a '(0 2)))))
    (is (equal '(6) (mx:shape (mx:squeeze (mx:reshape a '(1 6 1))))))
    (is (equal '(6 1) (mx:shape (mx:squeeze (mx:reshape a '(1 6 1)) :axis 0))))
    (is (equal '(3 2) (mx:shape (mx:swapaxes (mx:reshape a '(2 3)) 0 1))))
    (is (equal '(3 4 2) (mx:shape (mx:moveaxis (mx:zeros '(2 3 4)) 0 2))))
    (is (equal '(2 3) (mx:shape (mx:unflatten a 0 '(2 3)))))
    (is (equal '(1 2) (mx:shape (mx:atleast-2d (mx:ones '(2)) :stream nil))))))

(test joining-and-splitting
  (let ((a (mx:from-lisp '(1 2))) (b (mx:from-lisp '(3 4))))
    (is (close-to (mx:concatenate (list a b)) '(1 2 3 4)))
    (is (close-to (mx:concatenate (list (mx:reshape a '(1 2)) (mx:reshape b '(1 2))) :axis 1)
                  '((1 2 3 4))))
    (is (close-to (mx:stack (list a b)) '((1 2) (3 4))))
    (is (close-to (mx:stack (list a b) :axis 1) '((1 3) (2 4))))
    (is (equal '((2) (2) (2)) (mapcar #'mx:shape (mx:split (mx:arange 6) 3))))
    (is (equal '((1) (3) (2)) (mapcar #'mx:shape (mx:split (mx:arange 6) '(1 4)))))
    (is (close-to (mx:tile a '(2)) '(1 2 1 2)))
    (is (close-to (mx:repeat a 2) '(1 1 2 2)))
    (is (close-to (mx:broadcast-to a '(2 2)) '((1 2) (1 2))))
    (is (equal '((2 2) (2 2)) (mapcar #'mx:shape (mx:broadcast-arrays (list (mx:ones '(2 1)) (mx:ones '(2)))))))
    (is (equal '((3 2) (3 2)) (mapcar #'mx:shape (mx:meshgrid (list (mx:arange 2) (mx:arange 3))))))
    (destructuring-bind (q r) (mx:divmod (mx:from-lisp '(7)) (mx:from-lisp '(2)))
      (is (close-to q '(3)))
      (is (close-to r '(1))))))

(test padding
  (is (equal '(4 4) (mx:shape (mx:pad (mx:ones '(2 2)) 1))))
  (is (equal '(3 5) (mx:shape (mx:pad (mx:ones '(2 2)) '((0 1) (1 2))))))
  (is (close-to (mx:pad (mx:ones '(1)) 1 :constant-values 9) '(9 1 9)))
  (is (close-to (mx:pad (mx:from-lisp '(1 2)) 1 :mode "edge") '(1 1 2 2))))

(test sorting-and-selection
  (let ((a (mx:from-lisp '(3 1 2))))
    (is (close-to (mx:sort a) '(1 2 3)))
    (is (close-to (mx:argsort a) '(1 2 0)))
    (is (close-to (mx:sort (mx:from-lisp '((3 1) (2 4))) :axis 0) '((2 1) (3 4))))
    (is (close-to (mx:sort (mx:from-lisp '((3 1) (2 4))) :axis nil) '(1 2 3 4)))
    (is (close-to (mx:sort (mx:topk a 2)) '(2 3)))
    (is (= 3 (mx:size (mx:partition a 1))))
    (is (close-to (mx:take a (mx:from-lisp '(0 2))) '(3 2)))
    (is (close-to (mx:take (mx:from-lisp '((1 2) (3 4))) (mx:from-lisp '(1)) :axis 1) '((2) (4))))
    (is (close-to (mx:take-along-axis (mx:from-lisp '((10 20) (30 40))) (mx:from-lisp '((1) (0))) 1)
                  '((20) (30))))
    (is (close-to (mx:roll a 1) '(2 3 1)))
    (is (close-to (mx:clip (mx:from-lisp '(-5 0 5)) :a-min -1 :a-max 1) '(-1 0 1)))
    (is (close-to (mx:slice (mx:arange 10) '(2) '(8) :strides '(3)) '(2 5)))))

(test linear-algebra-ops
  (let ((a (mx:from-lisp '((1.0 2.0) (3.0 4.0)))))
    (is (close-to (mx:matmul a a) '((7 10) (15 22))))
    (is (close-to (mx:inner (mx:from-lisp '(1.0 2.0)) (mx:from-lisp '(3.0 4.0))) 11))
    (is (close-to (mx:outer (mx:from-lisp '(1.0 2.0)) (mx:from-lisp '(3.0 4.0))) '((3 4) (6 8))))
    (is (close-to (mx:tensordot a a :axes 1) '((7 10) (15 22))))
    (is (close-to (mx:tensordot a a :axes '((0 1) (0 1))) 30))
    (is (close-to (mx:trace a) 5))
    (is (close-to (mx:diagonal a) '(1 4)))
    (is (close-to (mx:diag (mx:from-lisp '(1 2))) '((1 0) (0 2))))
    (is (close-to (mx:tril a) '((1 0) (3 4))))
    (is (close-to (mx:triu a :k 1) '((0 2) (0 0))))
    (is (close-to (mx:kron (mx:eye 2) (mx:ones '(1 1))) '((1 0) (0 1))))
    (is (close-to (mx:einsum "ij,jk->ik" (list a a)) '((7 10) (15 22))))))

(test type-conversion
  (is (eq :int32 (mx:dtype (mx:astype (mx:ones '(2)) :int32))))
  (is (eq :float16 (mx:dtype (mx:astype (mx:ones '(2)) :float16))))
  (is (equal '(2) (mx:shape (mx:view (mx:ones '(1) :dtype :float32) :int16))))
  (is (close-to (mx:real (mx:from-lisp '(#c(1 2)))) '(1)))
  (is (close-to (mx:imag (mx:from-lisp '(#c(1 2)))) '(2)))
  (is (close-to (mx:stop-gradient (mx:ones '(1))) '(1)))
  (is (close-to (mx:nan-to-num (mx:divide (mx:scalar 0.0) (mx:scalar 0.0))) 0)))

(test convolution
  (let ((x (mx:ones '(1 5 1)))           ; NLC
        (w (mx:ones '(1 3 1))))          ; OKC
    (is (close-to (mx:conv1d x w) '(((3) (3) (3)))))
    (is (equal '(1 5 1) (mx:shape (mx:conv1d x w :padding 1)))))
  (is (equal '(1 3 3 1) (mx:shape (mx:conv2d (mx:ones '(1 5 5 1)) (mx:ones '(1 3 3 1)))))))

(test quantization
  (let* ((w (random:normal :shape '(64 64)))
         (q (mx:quantize w :group-size 32 :bits 4)))
    (is (= 3 (length q)))
    (destructuring-bind (wq scales biases) q
      (let ((back (mx:dequantize wq scales :biases biases :group-size 32 :bits 4)))
        (is (equal '(64 64) (mx:shape back)))
        (is (< (mx:item (mx:max (mx:abs (mx:subtract back w)))) 0.5))))))

(test errors-signal
  (signals mx:mlx-error (mx:matmul (mx:ones '(2 2)) (mx:ones '(3 3))))
  (signals mx:mlx-error (mx:reshape (mx:ones '(4)) '(3)))
  (handler-case (mx:reshape (mx:ones '(4)) '(3))
    (mx:mlx-error (e)
      (is (search "reshape" (mx:mlx-error-message e))))))

(test fast-ops
  (let ((x (random:normal :shape '(2 8))))
    (is (equal '(2 8) (mx:shape (fast:rms-norm x :weight (mx:ones '(8))))))
    (is (equal '(2 8) (mx:shape (fast:layer-norm x :weight (mx:ones '(8)) :bias (mx:zeros '(8))))))
    (is (close-to (mx:mean (fast:layer-norm x) :axis -1) '(0 0) 1e-3))
    (is (equal '(1 1 4 8) (mx:shape (fast:rope (mx:ones '(1 1 4 8)) 8 :base 10000.0))))
    (let ((q (random:normal :shape '(1 2 4 8))))
      (is (equal '(1 2 4 8) (mx:shape (fast:scaled-dot-product-attention q q q (/ 1.0 (sqrt 8.0))))))
      (is (equal '(1 2 4 8) (mx:shape (fast:scaled-dot-product-attention q q q 0.35
                                                                         :mask-mode "causal")))))))
